### ISSUE TITLE
Version content doesn't exist!

### ISSUE THREAD

**Issue by drwpow** [osulyanov/redactor2_rails#6]
Attempting to drop an image into Redactor 2. Using Carrierwave 1.1.0 and S3. On upload, it actually makes it to S3 just fine, but then throws this error:

```
ArgumentError (Version content doesn't exist!):
app/models/redactor2_rails/asset.rb:4:in `url'
ArgumentError: Version content doesn't exist!
```

This seems to be the part in Carrierwave that it doesn’t like: [uploader/versions.rb#202](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L202). Does this have something to do with the `url_content` method on `models/image.rb` and `models/file.rb`?

**Comment by drwpow** [comment]
Any chance somebody could look at this? This seems to be an issue with redactor2_rails, not Carrierwave, as I have no other issues with other Carrierwave uploaders.

**Comment by osulyanov** [comment]
@dangodev Have you configured `content` version in your Carrierwave uploader?

**Comment by osulyanov** [comment]
No answer for a while
